import type { Metadata } from "next";
import { Kavivanar } from 'next/font/google'
import "./globals.css";
import LenisSmoothScroll from "@/components/LenisSmoothScroll";
import Header from "@/components/header/Header";

const inter = Kavivanar({
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased overflow-x-hidden`}
      >
        <LenisSmoothScroll>
          <Header />
          {children}
        </LenisSmoothScroll>
      </body>
    </html>
  );
}
